// Research note — layout and wiring. All numbers come from
// includes/vars.typ and includes/*.csv, generated by scripts/build_report.py.
#import "/report/includes/vars.typ": n

#set page("a4", margin: (x: 1.5cm, top: 1.3cm, bottom: 1.5cm),
  footer: context [
    #set text(size: 7.5pt, fill: rgb("#898781"))
    Views my own; all data free and public. Not investment advice.
    #h(1fr) #counter(page).display("1 / 1", both: true)
  ])
#set text(size: 9.2pt, font: "Libertinus Serif")
#set par(justify: true, leading: 0.62em)
#show heading.where(level: 1): it => block(above: 1.1em, below: 0.6em)[
  #set text(size: 9.6pt, weight: "bold")
  #smallcaps(lower(it.body)) #v(-0.45em) #line(length: 100%, stroke: 0.5pt + rgb("#c3c2b7"))
]
#let accent = rgb("#b5541f")
#let muted = rgb("#52514e")
#let owner(body) = block(inset: (left: 6pt), stroke: (left: 1.5pt + accent))[
  #text(size: 8.2pt, fill: accent, weight: "bold")[OWNER — rewrite in your voice] \ #body]
#let csvtable(path, widths) = {
  let rows = csv(path)
  table(columns: widths, align: (x, y) => if x == 0 { left } else { right },
    stroke: none, inset: (y: 3.2pt),
    table.hline(stroke: 0.7pt), table.header(..rows.first().map(c => text(weight: "bold", size: 8pt)[#c])),
    table.hline(stroke: 0.4pt), ..rows.slice(1).flatten().map(c => text(size: 8.2pt)[#c]),
    table.hline(stroke: 0.7pt))
}

// ---------------- Page 1 ----------------
#block[
  #text(size: 15pt, weight: "bold")[Receive Brazil 5s10s: a #n.br_policy% Selic priced to stay] \
  #text(size: 9pt, fill: muted)[
    DV01-neutral 5s10s steepener in BR prefixado — paid #n.br_carry bp/3m to own the repricing of a cutting cycle the curve ignores. \
    #n.date · local-currency sovereign curve RV · data and code: `em-curve-rv` repo]
]
#v(0.5em)

#block(fill: rgb("#f6f4ef"), inset: 8pt, radius: 2pt, width: 100%)[
  #set text(size: 8.4pt)
  #grid(columns: (auto, 1fr, auto, 1fr), column-gutter: 10pt, row-gutter: 4.2pt,
    [*Trade*], [receive BR 5y, pay BR 10y (prefixado, NTN-F basis), DV01-neutral],
    [*Direction*], [steepener],
    [*Sizing*], [#n.br_ratio notional in 5y per 1.00 of 10y (zero-coupon DV01 basis)],
    [*Entry*], [5y #n.br_y5% / 10y #n.br_y10% → slope #n.br_slope bp],
    [*Carry + roll*], [#n.br_carry bp / 3m per unit DV01; #n.br_cv per unit of 3m vol (#n.br_vol bp)],
    [*Invalidation*], [slope #n.br_inval bp (1σ of 5y levels against; σ = #n.br_sigma5y bp)],
    [*Horizon*], [3m, rolled while thesis holds],
    [*Key risk*], [placeholder — R2],
  )
]

= Thesis
#owner[placeholder — R2 scaffold]

= What is priced
placeholder — R2

#figure(image("/output/figs/fig2_z_vs_cuts.png", width: 84%),
  caption: text(size: 8.2pt)[placeholder caption — R2])

#pagebreak()
// ---------------- Page 2 ----------------

= Carry across the candidate set
placeholder — R2

#figure(image("/output/figs/fig3_carry_per_vol.png", width: 92%),
  caption: text(size: 8.2pt)[placeholder caption — R2])

#grid(columns: (1.05fr, 1fr), column-gutter: 12pt,
  [
    = Cross-market state
    #csvtable("/report/includes/summary.csv", 9)
  ],
  [
    = What kills it
    placeholder — R2

    = Catalysts
    #owner[placeholder — R2 scaffold]
  ])

#figure(image("/output/figs/fig1_curves.png", width: 86%),
  caption: text(size: 8.2pt)[placeholder caption — R2])

#pagebreak()
// ---------------- Appendix ----------------

= Appendix A — method and conventions
placeholder — R2

= Appendix B — fit quality and data caveats
#csvtable("/report/includes/rmse.csv", 3)
placeholder — R2

= Appendix C — policy-path metric comparison
#csvtable("/report/includes/path_compare.csv", 3)
placeholder — R2

= Appendix D — provenance
Every number in this note maps to a generated variable:
#csvtable("/report/includes/provenance.csv", 3)

= Appendix E — with desk data I would extend by
placeholder — R2
