// Desk note — layout and wiring. Every number comes from includes/vars.typ
// and includes/*.csv, generated by scripts/build_report.py (no hand-typed
// figures). Content is frozen from Phase 2; this is the institutional restyle.
#import "/report/includes/vars.typ": n

#let ink = rgb("#0b0b0b")
#let muted = rgb("#52514e")
#let hair = rgb("#c3c2b7")
#let accent = rgb("#b5541f")
#let railbg = rgb("#f5f3ef")

#set page("a4", margin: (x: 1.7cm, top: 1.5cm, bottom: 1.6cm),
  footer: context [
    #set text(size: 7.5pt, fill: muted)
    #line(length: 100%, stroke: 0.4pt + hair)
    #v(2pt)
    Views my own; all data free and public. Not investment advice.
    #h(1fr)
    Priced to Stand Still · #n.date · #counter(page).display("1 of 1", both: true)
  ])
#set text(size: 9.3pt, font: "STIX Two Text", fill: ink)
#show math.equation: set text(font: "STIX Two Math")
#set par(justify: true, leading: 0.58em, spacing: 0.62em)

#show heading.where(level: 1): it => block(above: 0.9em, below: 0.5em)[
  #set text(size: 9.7pt, weight: "bold")
  #smallcaps(lower(it.body))
  #v(-0.42em) #line(length: 100%, stroke: 0.5pt + hair)
]

// booktabs-style table: no vertical rules, thin horizontals, right-aligned
// numerics with tabular figures, units live in the header.
#let booktabs(path, fs: 8.3pt) = {
  let rows = csv(path)
  set text(size: fs, number-width: "tabular")
  table(
    columns: rows.first().len(),
    align: (x, _) => if x == 0 { left } else { right },
    stroke: none, inset: (x: 5pt, y: 2.7pt),
    table.hline(stroke: 0.8pt),
    table.header(..rows.first().map(c => text(weight: "bold")[#c])),
    table.hline(stroke: 0.4pt),
    ..rows.slice(1).flatten(),
    table.hline(stroke: 0.8pt),
  )
}

#let owner(body) = block(inset: (left: 6pt), stroke: (left: 1.5pt + accent), below: 0.6em)[
  #text(size: 7.8pt, fill: accent, weight: "bold", tracking: 0.3pt)[OWNER — REWRITE IN YOUR VOICE]
  #v(-0.2em) #body]
#show figure.caption: it => align(center, block(width: 93%, above: 0.5em)[
  #set text(size: 8.1pt, fill: muted)
  #text(weight: "bold", fill: ink)[#it.supplement #context it.counter.display().] #it.body
])
#let railrow(label, body) = [
  #text(size: 7.3pt, fill: muted, weight: "bold", tracking: 0.2pt)[#upper(label)] \
  #text(size: 8.5pt)[#body]
  #v(3.5pt)
]

// ================= Header band =================
#block(width: 100%, below: 0.7em)[
  #text(size: 16pt, weight: "bold")[Priced to Stand Still]
  #h(6pt) #text(size: 11pt, fill: muted)[— receive Brazil 5s10s]
  #h(1fr) #text(size: 9pt, fill: muted)[#n.date]
  #v(-0.3em)
  #line(length: 100%, stroke: 1pt + ink)
  #v(2pt)
  #text(size: 8.6pt, fill: muted)[A #n.br_policy% Selic priced to stay: a DV01-neutral 5s10s steepener in Brazilian prefixado, paid #n.br_carry bp/3m to own a cutting cycle the curve ignores. Local-currency sovereign curve RV; data and code reproduce from a public repository.]
]

// ================= Page 1: main + right rail =================
#grid(columns: (1fr, 5.3cm), column-gutter: 14pt,
[
  == Thesis
  #owner[
    - The forward curve prices the Selic #n.br_path12 bp from #n.br_policy% a year out, a cutting cycle priced at zero. #text(fill: accent, size: 8pt)[[state your disinflation / real-rate view here]]
    - 5s10s sits at #n.br_slope bp against a 5y mean of #n.br_slope_mean5y bp (z #n.br_z). The belly carries no premium for the cycle; when cuts get priced, the 5y rallies against the 10y and the slope normalizes toward its mean.
    - The position pays #n.br_carry bp/3m per unit DV01 to wait. Being early costs nothing; being right is worth one to two $sigma$ (#n.br_sigma5y bp per $sigma$).
  ]

  == What is priced
  I read each fitted curve's short end as a policy path: the implied 3m rate 9m forward minus the current policy rate. Brazil is the only market where that number is negative, #n.br_path12 bp against a #n.br_policy% Selic. Mexico prices #n.mx_path12 bp from #n.mx_policy%, and the US and Germany sit between (table, p. 2). The metric inherits the 1y sector's term premium, so its level overstates hikes everywhere; the cross-market ranking, which is what the trade uses, survives that bias (Appendix C). Against this pricing, BR 5s10s is flat to its own 5y history while every other curve in the set is steep to normal, the combination the steepener monetizes.

  #figure(image("/output/figs/fig_z_vs_cuts.pdf", width: 100%),
    caption: [Brazil alone prices no cuts on a curve flat to history; the steepener needs the cycle _priced_, not delivered.])
],
[
  #block(fill: railbg, inset: 9pt, radius: 2pt, width: 100%)[
    #text(size: 8.2pt, weight: "bold", tracking: 0.4pt)[THE TRADE]
    #v(-0.15em) #line(length: 100%, stroke: 0.5pt + hair) #v(3pt)
    #railrow("Instruments")[receive BR 5y, pay BR 10y (prefixado, NTN-F basis)]
    #railrow("Direction")[DV01-neutral steepener]
    #railrow("Sizing")[#n.br_ratio in 5y per 1.00 of 10y; heavy discounting at #n.br_y10% equalizes zero-coupon DV01s]
    #railrow("Entry")[5y #n.br_y5% / 10y #n.br_y10%; slope #n.br_slope bp]
    #railrow("Carry + roll")[#n.br_carry bp per 3m per unit DV01; #n.br_cv per unit of 3m vol (#n.br_vol bp)]
    #railrow("Invalidation")[slope #n.br_inval bp, one 5y $sigma$ against ($sigma$ = #n.br_sigma5y bp)]
    #railrow("Horizon")[3m, rolled while the path stays unpriced]
    #railrow("Key risk")[renewed hikes flatten 5s10s through the exit; worst 3m of the past 5y is #n.kill_worst3m bp]
  ]
])

#pagebreak()
// ================= Page 2 =================
== Carry across the candidate set
Mexico's 2s10s steepener is the best-paid trade per unit of risk (#n.mx_carry bp/3m on #n.mx_vol bp vol, ratio #n.mx_cv), but it enters #n.mx_z $sigma$ steep to its 5y history with #n.mx_path12 bp of hikes already in the forwards, so its carry and its mean-reversion point in opposite directions. Brazil's ratio is smaller (#n.br_cv) and its signals agree. A cross-market check isolates the local story: BR minus US 5s10s sits at #n.box_level bp (z #n.box_z) and the two slopes' daily changes are uncorrelated (#n.box_corr), so Brazil's flatness is not imported global duration, it is local pricing.

#figure(image("/output/figs/fig_carry_per_vol.pdf", width: 86%),
  caption: [MX pays most per unit of risk but against a #n.mx_z $sigma$-steep slope; BR's smaller ratio buys a trade whose carry and z-score agree.])

== Cross-market state
#booktabs("/report/includes/summary.csv")
#text(size: 7.6pt, fill: muted)[C+R quoted for the steepener; Exit is the 1$sigma$ invalidation level for the positive-carry direction. Policy rates effective annual.]

#figure(image("/output/figs/fig_curves.pdf", width: 100%),
  caption: [Six months repriced every curve higher; Brazil un-inverted at the front, moving the cutting cycle out rather than pricing it in.])

#grid(columns: (1fr, 1fr), column-gutter: 16pt,
[
  == What kills it
  - *Flattening to the exit.* A move to #n.br_inval bp (#n.kill_move bp) erases #n.kill_quarters quarters of carry; I exit there rather than average.
  - *The realized tail.* The worst 3m flattening of the past 5y is #n.kill_worst3m bp (#n.kill_worst3m_when). A repeat swamps the #n.br_carry bp quarterly carry, this is a repricing trade, not a carry trade.
  - *Measurement.* My curve is retail (Tesouro Direto): #n.rb_5y bp vs interbank at 5y, #n.rb_10y bp at 10y. The #n.rb_5s10s bp differential biases the slope; a widening beyond the quarterly carry dominates measured P&L.
],
[
  == Catalysts
  #owner[
    - Copom communication that opens the door to easing; the front reprices first, the 5y follows hardest. #text(fill: accent, size: 8pt)[[your read on timing]]
    - Inflation prints versus target that validate the real-rate cushion at #n.br_policy% policy. #text(fill: accent, size: 8pt)[[your numbers]]
    - Fiscal news steepens the 10y independently: helps the trade, but for the wrong reason; I take profit, not add.
  ]
])

#pagebreak()
// ================= Appendix =================
== Appendix A — method and conventions
All yields are normalized to effective annual percent. Brazil's 252-business-day exponential quotes pass through unchanged; US and MX semiannual bond-equivalent yields compound to effective annual; Cetes convert from simple act/360 discount quotes. Policy rates share the basis: overnight act/360 quotes (Banxico target, fed funds upper bound, ECB deposit rate) convert via $(1 + r\/360)^365 - 1$; the Selic target is already effective annual. I fit Nelson-Siegel (Svensson where six or more tenors exist) by least squares, linear in the betas over a bounded $tau$ grid, no nonlinear optimizer, fully reproducible, storing RMSE per fit. Germany uses the Bundesbank's published Svensson parameters directly. Carry and rolldown are 3m static along today's fitted curve, funded at the policy rate, in bp per 3m per unit DV01 (zero-coupon approximation): $[h(y_T - r) + (T-h)(y_T - y_(T-h))] dot 10^4 \/ T$, with $h = 0.25$. Trade vol is the stdev of daily fitted-slope changes over 1y, scaled by $sqrt(66)$. Z-scores use 5y of slope levels. The invalidation rule exits when the slope moves one 5y standard deviation of levels, the z-score's own denominator, against the position.

== Appendix B — fit quality and data caveats
#booktabs("/report/includes/rmse.csv")
#v(3pt)
Brazil's curve fits Tesouro Direto retail mids: #n.rb_1y bp vs ANBIMA's interbank curve at 1y, #n.rb_5y bp at 5y, #n.rb_10y bp at 10y on the one cross-check date the public window allows. The level bias does not touch z-scores (the source is self-consistent through time); the tenor differential is the slope risk quantified on p. 2. Mexico's curve mixes weekly auction vintages (each tenor forward-filled at most 45 business days); the weekly-sampled vol cross-check reads #n.mx_vol_wk bp against #n.mx_vol bp daily-based, so the staleness discount to measured vol is nil. US and MX fit par yields while BR and DE are zero curves, a stated approximation that does not reorder 2s10s/5s10s carry-per-vol rankings.

== Appendix C — policy-path metric comparison
#booktabs("/report/includes/path_compare.csv")
#v(3pt)
The naive metric, $2 times ("1y" - "policy")$, reads Brazil at #n.br_naive bp of cuts because it linearly extrapolates the 1y point's dip below policy. The forward metric, the implied 3m rate 9m forward that the 1y and 9m points pin down, reads #n.br_path12 bp. I use the forward number: it is the curve's actual statement about the policy rate a year out. Both carry the 1y term premium; neither is a clean expectation. The cross-market ranking is the robust object, not the level.

== Appendix D — provenance
Every number in this note maps to a generated variable (provenance.csv, rebuilt by the report script):
#booktabs("/report/includes/provenance.csv", fs: 7pt)

== Appendix E — with desk data I would extend by
DI futures replace the retail curve (live, interbank, no basis caveat); ANBIMA's subscriber ETTJ history restores interbank z-scores; option-implied vol on DI futures replaces realized vol in the sizing denominator; a funding curve (GC repo vs Selic) replaces the policy-rate funding assumption; NTN-B breakevens split the nominal steepener into real-rate and inflation legs; and execution-cost estimates from quoted spreads turn carry-per-vol into carry-per-vol net of entry.
