// Research note — layout and wiring. All numbers come from
// includes/vars.typ and includes/*.csv, generated by scripts/build_report.py.
#import "/report/includes/vars.typ": n

#set page("a4", margin: (x: 1.5cm, top: 1.3cm, bottom: 1.5cm),
  footer: context [
    #set text(size: 7.5pt, fill: rgb("#898781"))
    Views my own; all data free and public. Not investment advice.
    #h(1fr) #counter(page).display("1 / 1", both: true)
  ])
#set text(size: 9.2pt, font: "STIX Two Text")
#show math.equation: set text(font: "STIX Two Math")
#set par(justify: true, leading: 0.56em)
#show heading.where(level: 1): it => block(above: 0.85em, below: 0.5em)[
  #set text(size: 9.6pt, weight: "bold")
  #smallcaps(lower(it.body)) #v(-0.45em) #line(length: 100%, stroke: 0.5pt + rgb("#c3c2b7"))
]
#let accent = rgb("#b5541f")
#let muted = rgb("#52514e")
#let owner(body) = block(inset: (left: 6pt), stroke: (left: 1.5pt + accent))[
  #text(size: 8.2pt, fill: accent, weight: "bold")[OWNER — rewrite in your voice] \ #body]
#let csvtable(path, widths, fs: 8.2pt) = {
  let rows = csv(path)
  table(columns: widths, align: (x, y) => if x == 0 { left } else { right },
    stroke: none, inset: (y: 2.6pt),
    table.hline(stroke: 0.7pt), table.header(..rows.first().map(c => text(weight: "bold", size: fs - 0.4pt)[#c])),
    table.hline(stroke: 0.4pt), ..rows.slice(1).flatten().map(c => text(size: fs)[#c]),
    table.hline(stroke: 0.7pt))
}

// ---------------- Page 1 ----------------
#block[
  #text(size: 15pt, weight: "bold")[Receive Brazil 5s10s: a #n.br_policy% Selic priced to stay] \
  #text(size: 9pt, fill: muted)[
    DV01-neutral 5s10s steepener in BR prefixado — paid #n.br_carry bp/3m to own the repricing of a cutting cycle the curve ignores. \
    #n.date · local-currency sovereign curve RV · data and code: `em-curve-rv` repo]
]
#v(0.4em)

#block(fill: rgb("#f6f4ef"), inset: 8pt, radius: 2pt, width: 100%)[
  #set text(size: 8.4pt)
  #grid(columns: (auto, 1fr, auto, 1fr), column-gutter: 10pt, row-gutter: 4.2pt,
    [*Trade*], [receive BR 5y, pay BR 10y (prefixado, NTN-F basis), DV01-neutral],
    [*Direction*], [steepener],
    [*Sizing*], [#n.br_ratio notional in 5y per 1.00 of 10y — at #n.br_y10% yields, discounting equalizes zero-coupon DV01s],
    [*Entry*], [5y #n.br_y5% / 10y #n.br_y10% → slope #n.br_slope bp],
    [*Carry + roll*], [#n.br_carry bp / 3m per unit DV01; #n.br_cv per unit of 3m vol (#n.br_vol bp)],
    [*Invalidation*], [slope #n.br_inval bp — 1σ of 5y levels against (σ = #n.br_sigma5y bp)],
    [*Horizon*], [3m, rolled while the path stays unpriced],
    [*Key risk*], [renewed hikes flatten 5s10s through the exit; the worst 3m flattening of the past 5y is #n.kill_worst3m bp],
  )
]

= Thesis
#owner[
  - The forward curve prices the Selic #n.br_path12 bp from #n.br_policy% a year out — a cutting cycle priced at zero. #text(fill: accent, size: 8pt)[\[state your disinflation / real-rate view here — why cuts come\]]
  - 5s10s sits at #n.br_slope bp against a 5y mean of #n.br_slope_mean5y bp (z #n.br_z). The belly carries no premium for the cycle; when cuts get priced, the 5y rallies against the 10y and the slope normalizes toward its mean.
  - The position pays #n.br_carry bp/3m per unit DV01 to wait. Being early costs nothing; being right is worth one to two σ (#n.br_sigma5y bp per σ).
]

= What is priced
I read each fitted curve's short end as a policy path: the implied 3m rate 9m
forward minus the current policy rate. Brazil is the only market where that
number is negative — #n.br_path12 bp against a #n.br_policy% Selic. Mexico
prices #n.mx_path12 bp from #n.mx_policy%, and the US and Germany sit between
(table, p. 2). The metric inherits the 1y sector's term premium, so its level
overstates hikes everywhere; the cross-market ranking, which is what the trade
uses, survives that bias (Appendix C). Against this pricing, BR 5s10s is flat
to its own 5y history while every other curve in the set is steep to normal —
the combination the steepener monetizes.

#figure(image("/output/figs/fig_z_vs_cuts.pdf"),
  caption: text(size: 8.2pt)[Brazil sits alone in the lower-left: no cuts priced, curve flat to history.
    The steepener needs the cycle to be *priced*, not delivered.])

#pagebreak()
// ---------------- Page 2 ----------------

= Carry across the candidate set
Mexico's 2s10s steepener is the best-paid trade per unit of risk
(#n.mx_carry bp/3m on #n.mx_vol bp vol, ratio #n.mx_cv) — but it enters
#n.mx_z σ steep to its 5y history with #n.mx_path12 bp of hikes already in the
forwards, so its carry and its mean-reversion point in opposite directions.
Brazil's ratio is smaller (#n.br_cv) and its signals agree. A cross-market
check isolates the local story: BR minus US 5s10s sits at #n.box_level bp
(z #n.box_z) and the two slopes' daily changes are uncorrelated (#n.box_corr),
so Brazil's flatness is not imported global duration — it is local pricing.

#figure(image("/output/figs/fig_carry_per_vol.pdf", width: 100%),
  caption: text(size: 8.2pt)[MX pays most per unit of risk but against a #n.mx_z σ-steep slope;
    BR's smaller ratio buys a trade whose carry and z-score agree.])

= Cross-market state
#csvtable("/report/includes/summary.csv", 9, fs: 8pt)
#text(size: 7.6pt, fill: muted)[C+R quoted for the steepener; Exit is the 1σ invalidation level for the positive-carry direction. Policy rates effective annual.]

#figure(image("/output/figs/fig_curves.pdf", width: 100%),
  caption: text(size: 8.2pt)[Six months repriced every curve higher; Brazil un-inverted at the front —
    the market moved the cutting cycle out rather than pricing it in.])

#grid(columns: (1fr, 1fr), column-gutter: 14pt,
  [
    = What kills it
    - *Flattening to the exit.* A move to #n.br_inval bp (#n.kill_move bp) erases #n.kill_quarters quarters of carry; I exit there rather than average.
    - *The realized tail.* The worst 3m flattening of the past 5y is #n.kill_worst3m bp (#n.kill_worst3m_when). A repeat swamps the #n.br_carry bp quarterly carry — this is a repricing trade, not a carry trade.
    - *Measurement.* My curve is retail (Tesouro Direto): #n.rb_5y bp vs interbank at 5y, #n.rb_10y bp at 10y. The #n.rb_5s10s bp differential biases the slope; a widening beyond the quarterly carry dominates measured P&L.
  ],
  [
    = Catalysts
    #owner[
      - Copom communication that opens the door to easing — the front reprices first, the 5y follows hardest. #text(fill: accent, size: 8pt)[\[your read on timing\]]
      - Inflation prints versus target that validate the real-rate cushion at #n.br_policy% policy. #text(fill: accent, size: 8pt)[\[your numbers\]]
      - Fiscal news steepens the 10y independently — helps the trade, but for the wrong reason; I would take profit, not add.
    ]
  ])

#pagebreak()
// ---------------- Appendix ----------------

= Appendix A — method and conventions
All yields are normalized to effective annual percent. Brazil's 252-business-day
exponential quotes pass through unchanged; US and MX semiannual bond-equivalent
yields compound to effective annual; Cetes convert from simple act/360 discount
quotes. Policy rates share the basis: overnight act/360 quotes (Banxico target,
fed funds upper bound, ECB deposit rate) convert via $(1 + r\/360)^365 - 1$;
the Selic target is already effective annual. I fit Nelson-Siegel (Svensson
where six or more tenors exist) by least squares, linear in the betas over a
bounded τ grid — no nonlinear optimizer, fully reproducible — and store RMSE
per fit. Germany uses the Bundesbank's published Svensson parameters directly.
Carry and rolldown are 3m static along today's fitted curve, funded at the
policy rate, in bp per 3m per unit DV01 (zero-coupon approximation):
$[h(y_T - r) + (T-h)(y_T - y_(T-h))] dot 10^4\/T$, $h = 0.25$. Trade vol is
the stdev of daily fitted-slope changes over 1y, scaled by $sqrt(66)$.
Z-scores use 5y of slope levels. The invalidation rule exits when the slope
moves one 5y standard deviation of levels — the z-score's own denominator —
against the position from entry.

= Appendix B — fit quality and data caveats
#csvtable("/report/includes/rmse.csv", 3)
Brazil's curve fits Tesouro Direto retail mids: #n.rb_1y bp vs ANBIMA's
interbank curve at 1y, #n.rb_5y bp at 5y, #n.rb_10y bp at 10y on the one
cross-check date the public window allows. The level bias does not touch
z-scores (the source is self-consistent through time); the tenor differential
is the slope risk quantified on p. 2. Mexico's curve mixes weekly auction
vintages (each tenor forward-filled at most 45 business days); the weekly-
sampled vol cross-check reads #n.mx_vol_wk bp against #n.mx_vol bp daily-based,
so the staleness discount to measured vol is nil. US and MX fit par yields
while BR and DE are zero curves — a stated approximation that does not reorder
2s10s/5s10s carry-per-vol rankings.

= Appendix C — policy-path metric comparison
#csvtable("/report/includes/path_compare.csv", 3)
The naive metric, $2 times ("1y" - "policy")$, reads Brazil at #n.br_naive bp
of cuts because it linearly extrapolates the 1y point's dip below policy. The
forward metric — the implied 3m rate 9m forward, which the 1y and 9m points
pin down — reads #n.br_path12 bp. I use the forward number: it is the
curve's actual statement about the policy rate a year out. Both carry the 1y
term premium; neither is a clean expectation. The cross-market ranking is the
robust object, not the level.

= Appendix D — provenance
Every number in this note maps to a generated variable
(`report/includes/provenance.csv`, rebuilt by `scripts/build_report.py`):
#csvtable("/report/includes/provenance.csv", 3, fs: 7pt)

= Appendix E — with desk data I would extend by
DI futures replace the retail curve (live, interbank, no basis caveat);
ANBIMA's subscriber ETTJ history restores interbank z-scores; option-implied
vol on DI futures replaces realized vol in the sizing denominator; a funding
curve (GC repo vs Selic) replaces the policy-rate funding assumption; NTN-B
breakevens split the nominal steepener into real-rate and inflation legs; and
execution-cost estimates from quoted spreads turn carry-per-vol into
carry-per-vol net of entry.
